name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{secrets.ACR_USER}}
          password: ${{secrets.ACR_PWD}}
          login-server: webflaskapplication.azurecr.io
      - run: |
          docker build -f src/Dockerfile -t sample/produto-api:v2 .
          docker push sample/produto-api:v2
