name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{secrets.ACR_USER}}
          password: ${{secrets.ACR_PWD}}
          login-server: webflaskapplication.azurecr.io
      - run: |
          docker build /scr/Dockerfile -t webflaskapplication.azurecr.io/produto-api:v2
          docker push webflaskapplication.azurecr.io/produto-api:v2
